FROM node:20-alpine

WORKDIR /app

# Устанавливаем оригинальный json-server глобально
RUN npm install -g json-server

RUN mkdir -p fixtures


EXPOSE 3000

# Запускаем сервер, указывая на тестовый файл в папке fixtures
CMD ["json-server", "--watch", "fixtures/db.json", "--host", "0.0.0.0", "--port", "3000"]